server:
  port: 8088

spring:
  messages:
    basename: messages
  security:
    user:
      name: rhtmdwh
      password: tmdwh741

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"
